name: NPM Publish

on:
  workflow_dispatch:
  push:
    branches:
      #       - main
      - sander/autoPublish

jobs:
  npm_publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checking out
        uses: actions/checkout@master
      - name: Installing node
        uses: actions/setup-node@master
        with:
          node-version: '14'
      - name: Download build hashes
        uses: actions/download-artifact@v2
        with:
          name: releaseChecksums.json
      - name: Installing packages, build, and publish libs
        run: |
          npm config set //registry.npmjs.org/:_authToken ${NPM_TOKEN}
          npm ci --ignore-scripts
          npm run auto-publish-nightly
        env:
          PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: true
          CYPRESS_INSTALL_BINARY: 0
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Archive build hashes
        uses: actions/upload-artifact@v2
        with:
          name: releaseChecksums.json
          path: releaseChecksums.json
          retention-days: 365
