name: NPM Publish

on:
  workflow_dispatch:
  push:
    branches:
      #       - main
      - sander/autoPublish

jobs:
  npm_publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checking out
        uses: actions/checkout@master
      - name: Installing node
        uses: actions/setup-node@master
        with:
          node-version: '14'
      - name: Installing packages
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: true
          CYPRESS_INSTALL_BINARY: 0
        run: npm ci --ignore-scripts
      - name: Build and publish libs
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm run auto-publish-nightly
