name: NPM Publish

on:
  # workflow_dispatch:
  push:
    branches:
      #       - main
      - sander/autoPublish

jobs:
  build code:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: '14'
        env:
          PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: true
          CYPRESS_INSTALL_BINARY: 0
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - run: npm ci --ignore-scripts
      - run: npx tsc -p tsconfig.tool.json
      - run: npm run auto-publish-nightly
